name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run:
        python3 -m venv .venv
        pip3 install --user django
        source .venv/bin/activate
        python3 manage.py test