name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
    - name: Run Django unit tests
      with:
        python-version: '3.10'
      run:
        python manage.py test